name: Build - MacOS

on: [push, pull_request, workflow_dispatch]

jobs:
  macos:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: brew install SDL2 SDL2_image SDL2_mixer SDL2_ttf

      - name: Configure
        run: cmake
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DINSTALL_PORTABLE=ON
          -DENABLE_LOCALES=OFF
          -DUSE_BUNDLED_SDL2=ON
          -DCMAKE_POLICY_VERSION_MINIMUM="3.5"

      - name: Build
        run: cmake --build build --verbose

      - name: Deploy
        run: cmake --install build --strip --prefix install
